### PR TITLE
feature/INTERLOK-3064 - services inside conditions

### PR DESCRIPTION
**Pull request by albinoloverats**
## Motivation

The service-tester does not support testing individual services inside conditions (if/switch etc).

## Modification

Add an extra `/` to the XPath used to identify services in the `ServiceUniqueIdPreprocessor`. This will mean that the XPath will find the service with the given unique ID at any point below the matched channel & workflow, and not just as a immediate child.

## PR Checklist

- [x] been self-reviewed.
- [x] Added unit tests or modified existing tests to cover new code paths
- [x] Tested new/updated components in the UI and at runtime in an Interlok instance
- [x] Checked the display of the component in the UI

## Result

The user can now identify a service within a conditional as a descendent of a given channel & workflow. An alternative workaround would be not to set a channel or workflow and the generated XPath would already find the required service.

## Testing

Find [attached](https://github.com/adaptris/interlok-service-tester/files/6785183/switch-test.zip) a project with adapter config and service-tester config. There is a test case the targets one of the services within the switch service.

### CODE REVIEW

**Comment by sebastien-belin-adp** [comment]
@albinoloverats I'm wondering with this solution what will happen if two services use the same unique id but at different level.
For instance in the xml example used in ServiceUniqueIdPreprocessorTest#testServiceInCondition, if in the workflow service list there is another service (whatever it is) with the unique-id "json-case", the ServiceUniqueIdPreprocessor will struggle to find the right service?

So I still think the ServiceUniqueIdPreprocessor need the full list of "parent" unique id to be more accurate.

`new ServiceUniqueIdPreprocessor("channel", "workflow", Collections.singletonList("switch", "json-case"));`
How does that work for the xpath? I'm not really sure yet.

**Comment by albinoloverats** [comment]
@sebastien-belin-adp If there are multiple services with the same unique ID, then it just tests the first that the XPath matches. Although this would also happen if the user didn't specify a channel or workflow.

I can certainly dig deeper and try to get the ID's of the conditionals passed to the `ServiceUniqueIdPreprocessor` constructor.

**Comment by sebastien-belin-adp** [comment]
@albinoloverats I understand why you did what you did and in fairness I didn't find any good alternative yet.
But I wonder if this change of behavior can be an issue.

**Comment by albinoloverats** [comment]
I have a alternative suggestion over [in the UI](https://gitlab.agb.rbxd.ds/interlok/interlok-ui/-/merge_requests/68), if anyone is interested.

**Comment by sebastien-belin-adp** [comment]
The changes in the UI will help if using but we may still have an issue when not using the UI :s.

However thanks for the change in the UI. I'll check that.

**Comment by sebastien-belin-adp** [comment]
I like the new changes. We will just have to think about updating that if we ever add some new special services with nested services.
I've added a couple more tests to deal with IfElse services.

**Review by sebastien-belin-adp — APPROVED** [review]

**Pull request merged**
